# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmap', '0002_auto_20181106_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtp_area',
            name='Name',
            field=models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0443\u0447\u0430\u0441\u0442\u043a\u0430'),
        ),
    ]
